### ISSUE TITLE
rn-link does not handle refactored file names well.

### ISSUE THREAD

**Issue by chrisajimenez** [Swaagie/react-native-yunolink#1]
The way rn-link seemingly syncs changes between the code being linked and the source node_modules code breaks the metro bundler in cases where multiple files with similar paths exists. For example:

both `src/components/dropdown.js` and `src/components/dropdown/index.js` can be legally resolved by:
```js
import dropdown from './components/dropdown';
```

rn-link can trigger this if the linked code is refactored and files/paths are renamed differently than the code the lives in the node_modules of the source directory.

`projectA/node_modules/dropdown/dropdown.js`

`dropdown/src/dropdown/index.js`

running `rn-link ../dropdown` inside of `projectA` causes both file structures to exist in the `projectA/node_modules/dropdown` in this case.

**Comment by Swaagie** [comment]
Thanks for reporting, this is due to `rsync` usage. It will syncs downstream and thus will leave any other files that exist like `projectA/node_modules/dropdown/dropdown.js` around even if it was deleted from source.

Two options here:
1. Check for `unlink` events in `chokidar` and delete files or folders upstream.
2. Listen to a custom signal like `SIGINT` to start fresh and reset. Basically remove the target and have sync every file again from source after.

The first option seems to be most clean.
